//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xiaomi_Flash.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xiaomi_Flash.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Xiaomi Flash.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Basado en FastbootEnhance por LibXZR.
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desactivado.
        /// </summary>
        public static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activado.
        /// </summary>
        public static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconocido.
        /// </summary>
        public static string fastboot_0_size {
            get {
                return ResourceManager.GetString("fastboot_0_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades básicas.
        /// </summary>
        public static string fastboot_basic_prop {
            get {
                return ResourceManager.GetString("fastboot_basic_prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar actualización pendiente.
        /// </summary>
        public static string fastboot_cancel_update {
            get {
                return ResourceManager.GetString("fastboot_cancel_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doble clic para seleccionar el dispositivo:.
        /// </summary>
        public static string fastboot_choose_device {
            get {
                return ResourceManager.GetString("fastboot_choose_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Virtual A/B temporary partitions exist.
        /// </summary>
        public static string fastboot_cow_exist_str0 {
            get {
                return ResourceManager.GetString("fastboot_cow_exist_str0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The temporary partitions created during the Virtual A/B system update exist in the device, forcing it to continue may cause the flashing to fail due to insufficient space in the super partition, and thus brick the device..
        /// </summary>
        public static string fastboot_cow_exist_str1 {
            get {
                return ResourceManager.GetString("fastboot_cow_exist_str1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ( You can manually delete the temporary partitions ending in &quot;cow&quot; to resolve this warning if the Virtual A/B update is not in progress ).
        /// </summary>
        public static string fastboot_cow_exist_str2 {
            get {
                return ResourceManager.GetString("fastboot_cow_exist_str2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Would you like to continue?.
        /// </summary>
        public static string fastboot_cow_exist_str3 {
            get {
                return ResourceManager.GetString("fastboot_cow_exist_str3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create new logical partition.
        /// </summary>
        public static string fastboot_create_dynamic_partition {
            get {
                return ResourceManager.GetString("fastboot_create_dynamic_partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo actual: .
        /// </summary>
        public static string fastboot_current_device {
            get {
                return ResourceManager.GetString("fastboot_current_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Slot actual.
        /// </summary>
        public static string fastboot_current_slot {
            get {
                return ResourceManager.GetString("fastboot_current_slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo.
        /// </summary>
        public static string fastboot_device {
            get {
                return ResourceManager.GetString("fastboot_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del dispositivo.
        /// </summary>
        public static string fastboot_device_name {
            get {
                return ResourceManager.GetString("fastboot_device_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Target device is not exist.
        /// </summary>
        public static string fastboot_device_not_exist {
            get {
                return ResourceManager.GetString("fastboot_device_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fastboot.
        /// </summary>
        public static string fastboot_enhance {
            get {
                return ResourceManager.GetString("fastboot_enhance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expand logical partition.
        /// </summary>
        public static string fastboot_expand_dynamic_partition {
            get {
                return ResourceManager.GetString("fastboot_expand_dynamic_partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar por nombre:.
        /// </summary>
        public static string fastboot_filter_by_partition_name {
            get {
                return ResourceManager.GetString("fastboot_filter_by_partition_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flashear Payload.bin.
        /// </summary>
        public static string fastboot_flash_payload {
            get {
                return ResourceManager.GetString("fastboot_flash_payload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignorar particiones desconocidas.
        /// </summary>
        public static string fastboot_ignore_unknown {
            get {
                return ResourceManager.GetString("fastboot_ignore_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En Fastbootd.
        /// </summary>
        public static string fastboot_is_userspace {
            get {
                return ResourceManager.GetString("fastboot_is_userspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This operation does not allow multiple partitions to be selected..
        /// </summary>
        public static string fastboot_not_support_multiselect {
            get {
                return ResourceManager.GetString("fastboot_not_support_multiselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This operation is only supported for logical partitions..
        /// </summary>
        public static string fastboot_only_logical {
            get {
                return ResourceManager.GetString("fastboot_only_logical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string fastboot_partition_action {
            get {
                return ResourceManager.GetString("fastboot_partition_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string fastboot_partition_action_create {
            get {
                return ResourceManager.GetString("fastboot_partition_action_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string fastboot_partition_action_delete {
            get {
                return ResourceManager.GetString("fastboot_partition_action_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string fastboot_partition_action_erase {
            get {
                return ResourceManager.GetString("fastboot_partition_action_erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flashear.
        /// </summary>
        public static string fastboot_partition_action_flash {
            get {
                return ResourceManager.GetString("fastboot_partition_action_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redimensionar.
        /// </summary>
        public static string fastboot_partition_action_resize {
            get {
                return ResourceManager.GetString("fastboot_partition_action_resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es lógica.
        /// </summary>
        public static string fastboot_partition_is_dynamic {
            get {
                return ResourceManager.GetString("fastboot_partition_is_dynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string fastboot_partition_name {
            get {
                return ResourceManager.GetString("fastboot_partition_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partition name is empty..
        /// </summary>
        public static string fastboot_partition_name_empty {
            get {
                return ResourceManager.GetString("fastboot_partition_name_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño.
        /// </summary>
        public static string fastboot_partition_size {
            get {
                return ResourceManager.GetString("fastboot_partition_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño (B).
        /// </summary>
        public static string fastboot_partition_size_b {
            get {
                return ResourceManager.GetString("fastboot_partition_size_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partition size is empty..
        /// </summary>
        public static string fastboot_partition_size_empty {
            get {
                return ResourceManager.GetString("fastboot_partition_size_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid partition size..
        /// </summary>
        public static string fastboot_partition_size_invalid {
            get {
                return ResourceManager.GetString("fastboot_partition_size_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to shrink a partition. You can delete and recreate it..
        /// </summary>
        public static string fastboot_partition_size_unable_shrink {
            get {
                return ResourceManager.GetString("fastboot_partition_size_unable_shrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Particiones.
        /// </summary>
        public static string fastboot_partition_table {
            get {
                return ResourceManager.GetString("fastboot_partition_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string fastboot_prop_name {
            get {
                return ResourceManager.GetString("fastboot_prop_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string fastboot_prop_value {
            get {
                return ResourceManager.GetString("fastboot_prop_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reiniciar a Bootloader.
        /// </summary>
        public static string fastboot_reboot_bootloader {
            get {
                return ResourceManager.GetString("fastboot_reboot_bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reiniciar a Fastbootd.
        /// </summary>
        public static string fastboot_reboot_fastbootd {
            get {
                return ResourceManager.GetString("fastboot_reboot_fastbootd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reiniciar a Recovery.
        /// </summary>
        public static string fastboot_reboot_recovery {
            get {
                return ResourceManager.GetString("fastboot_reboot_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reiniciar al sistema.
        /// </summary>
        public static string fastboot_reboot_system {
            get {
                return ResourceManager.GetString("fastboot_reboot_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconectar.
        /// </summary>
        public static string fastboot_remove_device {
            get {
                return ResourceManager.GetString("fastboot_remove_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualización seamless.
        /// </summary>
        public static string fastboot_seamless_update {
            get {
                return ResourceManager.GetString("fastboot_seamless_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secure Boot.
        /// </summary>
        public static string fastboot_secure_boot {
            get {
                return ResourceManager.GetString("fastboot_secure_boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de serie.
        /// </summary>
        public static string fastboot_serial_num {
            get {
                return ResourceManager.GetString("fastboot_serial_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar slot A.
        /// </summary>
        public static string fastboot_setactive_a {
            get {
                return ResourceManager.GetString("fastboot_setactive_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar slot B.
        /// </summary>
        public static string fastboot_setactive_b {
            get {
                return ResourceManager.GetString("fastboot_setactive_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar logs.
        /// </summary>
        public static string fastboot_show_logs {
            get {
                return ResourceManager.GetString("fastboot_show_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Target partition not yet selected..
        /// </summary>
        public static string fastboot_target_partition_not_selected {
            get {
                return ResourceManager.GetString("fastboot_target_partition_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The following partitions to flash may be unknown:.
        /// </summary>
        public static string fastboot_unknown_partition_str0 {
            get {
                return ResourceManager.GetString("fastboot_unknown_partition_str0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can check the &quot;Ignore unknown partitions&quot; checkbox to disable this warning, the presence of unknown partitions does not mean that the flashing will fail or the device will brick..
        /// </summary>
        public static string fastboot_unknown_partition_str1 {
            get {
                return ResourceManager.GetString("fastboot_unknown_partition_str1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You may need to reboot to fastbootd mode..
        /// </summary>
        public static string fastboot_unknown_partition_str2 {
            get {
                return ResourceManager.GetString("fastboot_unknown_partition_str2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de actualización.
        /// </summary>
        public static string fastboot_update_status {
            get {
                return ResourceManager.GetString("fastboot_update_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fusionando.
        /// </summary>
        public static string fastboot_update_status_merging {
            get {
                return ResourceManager.GetString("fastboot_update_status_merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ninguno.
        /// </summary>
        public static string fastboot_update_status_none {
            get {
                return ResourceManager.GetString("fastboot_update_status_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Snapshot creado.
        /// </summary>
        public static string fastboot_update_status_snapshotted {
            get {
                return ResourceManager.GetString("fastboot_update_status_snapshotted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System update is in progress.
        /// </summary>
        public static string fastboot_vab_staging_str0 {
            get {
                return ResourceManager.GetString("fastboot_vab_staging_str0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The device is in the process of system update, forcing the operation may brick the device..
        /// </summary>
        public static string fastboot_vab_staging_str1 {
            get {
                return ResourceManager.GetString("fastboot_vab_staging_str1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ( You can reboot the device to the system and wait a while until the update process is complete ).
        /// </summary>
        public static string fastboot_vab_staging_str2 {
            get {
                return ResourceManager.GetString("fastboot_vab_staging_str2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Would you like to continue?.
        /// </summary>
        public static string fastboot_vab_staging_str3 {
            get {
                return ResourceManager.GetString("fastboot_vab_staging_str3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Would you like to disable the verification in vbmeta?.
        /// </summary>
        public static string fastboot_vbmeta_disable_verify {
            get {
                return ResourceManager.GetString("fastboot_vbmeta_disable_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable verification.
        /// </summary>
        public static string fastboot_vbmeta_disable_verify_title {
            get {
                return ResourceManager.GetString("fastboot_vbmeta_disable_verify_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string logger {
            get {
                return ResourceManager.GetString("logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código fuente.
        /// </summary>
        public static string open_source {
            get {
                return ResourceManager.GetString("open_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación completada.
        /// </summary>
        public static string operation_completed {
            get {
                return ResourceManager.GetString("operation_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation is not supported..
        /// </summary>
        public static string operation_not_supported {
            get {
                return ResourceManager.GetString("operation_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades básicas.
        /// </summary>
        public static string payload_basic_properties {
            get {
                return ResourceManager.GetString("payload_basic_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blocksize.
        /// </summary>
        public static string payload_blocksize {
            get {
                return ResourceManager.GetString("payload_blocksize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Examinar.
        /// </summary>
        public static string payload_browse {
            get {
                return ResourceManager.GetString("payload_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo actual: .
        /// </summary>
        public static string payload_current_file {
            get {
                return ResourceManager.GetString("payload_current_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Blobs Size.
        /// </summary>
        public static string payload_data_size {
            get {
                return ResourceManager.GetString("payload_data_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extractor Payload.
        /// </summary>
        public static string payload_dumper {
            get {
                return ResourceManager.GetString("payload_dumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dynamic Partition Metadata.
        /// </summary>
        public static string payload_dynamic_partition_metadata {
            get {
                return ResourceManager.GetString("payload_dynamic_partition_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has occurred..
        /// </summary>
        public static string payload_error_occur {
            get {
                return ResourceManager.GetString("payload_error_occur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignore unknown operations.
        /// </summary>
        public static string payload_extract_ignore_unknown {
            get {
                return ResourceManager.GetString("payload_extract_ignore_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignore checksum.
        /// </summary>
        public static string payload_extract_ignore_verify {
            get {
                return ResourceManager.GetString("payload_extract_ignore_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extraer imagen.
        /// </summary>
        public static string payload_extract_image {
            get {
                return ResourceManager.GetString("payload_extract_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow incremental.
        /// </summary>
        public static string payload_extract_incremental {
            get {
                return ResourceManager.GetString("payload_extract_incremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extracting options.
        /// </summary>
        public static string payload_extract_options {
            get {
                return ResourceManager.GetString("payload_extract_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full Package.
        /// </summary>
        public static string payload_full_package {
            get {
                return ResourceManager.GetString("payload_full_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to extract images from an incremental package..
        /// </summary>
        public static string payload_incremental_warning {
            get {
                return ResourceManager.GetString("payload_incremental_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manifest Size.
        /// </summary>
        public static string payload_manifest_size {
            get {
                return ResourceManager.GetString("payload_manifest_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metadata Signatures (Base64).
        /// </summary>
        public static string payload_metadata_signature {
            get {
                return ResourceManager.GetString("payload_metadata_signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metadata Signatures Size.
        /// </summary>
        public static string payload_metadata_signature_size {
            get {
                return ResourceManager.GetString("payload_metadata_signature_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No dynamic partition metadata.
        /// </summary>
        public static string payload_no_dynamic_metadata {
            get {
                return ResourceManager.GetString("payload_no_dynamic_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No payload has been specified, click the button browse, or drag in a file..
        /// </summary>
        public static string payload_no_file_str {
            get {
                return ResourceManager.GetString("payload_no_file_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partitions Included: .
        /// </summary>
        public static string payload_partition_group_include {
            get {
                return ResourceManager.GetString("payload_partition_group_include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partition Group Name: .
        /// </summary>
        public static string payload_partition_group_name {
            get {
                return ResourceManager.GetString("payload_partition_group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partition Group Size: .
        /// </summary>
        public static string payload_partition_group_size {
            get {
                return ResourceManager.GetString("payload_partition_group_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Particiones.
        /// </summary>
        public static string payload_partitions {
            get {
                return ResourceManager.GetString("payload_partitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar por nombre:.
        /// </summary>
        public static string payload_partitions_filter_by_name {
            get {
                return ResourceManager.GetString("payload_partitions_filter_by_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Checksum (Base64).
        /// </summary>
        public static string payload_partitions_hash {
            get {
                return ResourceManager.GetString("payload_partitions_hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string payload_partitions_name {
            get {
                return ResourceManager.GetString("payload_partitions_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño.
        /// </summary>
        public static string payload_partitions_size {
            get {
                return ResourceManager.GetString("payload_partitions_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string payload_property_name {
            get {
                return ResourceManager.GetString("payload_property_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string payload_property_value {
            get {
                return ResourceManager.GetString("payload_property_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar.
        /// </summary>
        public static string payload_remove_file {
            get {
                return ResourceManager.GetString("payload_remove_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Signatures (Base64).
        /// </summary>
        public static string payload_signature {
            get {
                return ResourceManager.GetString("payload_signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Signatures Size.
        /// </summary>
        public static string payload_signature_size {
            get {
                return ResourceManager.GetString("payload_signature_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Snapshot enabled: .
        /// </summary>
        public static string payload_snapshot_enabled {
            get {
                return ResourceManager.GetString("payload_snapshot_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Target partitions to extract not yet selected..
        /// </summary>
        public static string payload_target_partition_not_selected {
            get {
                return ResourceManager.GetString("payload_target_partition_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timestamp.
        /// </summary>
        public static string payload_timestamp {
            get {
                return ResourceManager.GetString("payload_timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to drop multiple files..
        /// </summary>
        public static string payload_unable_drop_multifile {
            get {
                return ResourceManager.GetString("payload_unable_drop_multifile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incompatible file format..
        /// </summary>
        public static string payload_unsupported_format {
            get {
                return ResourceManager.GetString("payload_unsupported_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payload Version.
        /// </summary>
        public static string payload_version {
            get {
                return ResourceManager.GetString("payload_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El programa ya está en ejecución.
        /// </summary>
        public static string program_already_running {
            get {
                return ResourceManager.GetString("program_already_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión 2.0 — Proyecto Final Xiaomi Flash.
        /// </summary>
        public static string release_at {
            get {
                return ResourceManager.GetString("release_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona la ruta de guardado.
        /// </summary>
        public static string select_save_path {
            get {
                return ResourceManager.GetString("select_save_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconocido.
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Créditos originales.
        /// </summary>
        public static string visit_thread {
            get {
                return ResourceManager.GetString("visit_thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
